[package]
name = "goose-mcp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[lints]
workspace = true

[features]
default = ["bundled-mcp"]
rustls-tls = []
native-tls = []
autovisualiser = []
computer-controller = ["dep:lopdf", "dep:docx-rs", "dep:image", "dep:umya-spreadsheet"]
document-tools = ["computer-controller"]
memory-server = []
tutorial-server = ["dep:include_dir"]
bundled-mcp = ["autovisualiser", "computer-controller", "document-tools", "memory-server", "tutorial-server"]

[dependencies]
rmcp = { workspace = true, features = ["server", "client", "transport-io", "macros"] }
anyhow = { workspace = true }
tokio = { workspace = true, features = ["process", "io-util"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing-appender = { workspace = true }
base64 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
schemars = { workspace = true }
indoc = { workspace = true }
chrono = { workspace = true }
etcetera = { workspace = true }
tempfile = { workspace = true }
include_dir = { workspace = true, optional = true }
once_cell = { workspace = true }
lopdf = { version = "0.45", default-features = false, optional = true }
docx-rs = { version = "0.4.18", default-features = false, features = ["image"], optional = true }
image = { version = "0.24.4", default-features = false, features = ["bmp", "dds", "dxt", "farbfeld", "gif", "hdr", "ico", "jpeg", "jpeg_rayon", "openexr", "png", "pnm", "tga", "tiff", "webp"], optional = true }
umya-spreadsheet = { version = "3", default-features = false, optional = true }
shell-words = { workspace = true }
process-wrap = { version = "9", default-features = false, features = ["std", "process-session"] }
