[package]
name = "goose-agent"
version = "0.1.0-alpha.11"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "The GDK's Agent Loop"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true, features = ["macros", "sync", "rt", "time"] }
tokio-util = { workspace = true, features = ["compat"] }
async-trait = { workspace = true }
goose-provider-types = { version = "0.1.0-alpha.11", path = "../goose-provider-types", default-features = false }
rmcp = { workspace = true, features = ["server"] }
uuid = { workspace = true }
serde_json = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
tracing-futures = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
rmcp = { workspace = true, features = ["local"] }

[dev-dependencies]
schemars.workspace = true
serde = { workspace = true, features = ["derive"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
js-sys = "0.3.105"
wasm-bindgen-futures = "0.4.78"
wasm-bindgen-test = "0.3.78"
